In [4]:
import numpy as np
x1=np.array([1,2,5,66])
x2=np.array([[1,2,3],[4,5,6]])
print("x1:",x1)
print("x2:",x2)

x1: [ 1  2  5 66]
x2: [[1 2 3]
 [4 5 6]]


In [5]:
x1[0] #access 1st element 

1

In [7]:
x1[-1] #access last element

66

In [8]:
x1[0:2]

array([1, 2])

In [9]:
x1[0]+x1[-1]

67

In [10]:
x1[0: :3]

array([ 1, 66])

In [12]:
x1[0::2]

array([1, 5])

In [13]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x2[0]

array([1, 2, 3])

In [16]:
x2[:,0]

array([1, 4])

In [17]:
x2[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x2[:,2]

array([3, 6])

In [19]:
x2[0][2]

3

In [22]:
x2[:,0:2]

array([[1, 2],
       [4, 5]])

In [23]:
x2[:,0::2]

array([[1, 3],
       [4, 6]])

In [24]:
for i in x2:
    print(i)

[1 2 3]
[4 5 6]


In [25]:
x3=np.array([[[1,2,3],[5,6,7],[8,9,10]]])

In [26]:
x3

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [29]:
x3[0]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [32]:
x3[0][0]

array([1, 2, 3])

In [34]:
x3[0][0:2]

array([[1, 2, 3],
       [5, 6, 7]])

In [35]:
x3[0][:,0]

array([1, 5, 8])

In [36]:
x3[0:,0:,0]

array([[1, 5, 8]])

In [37]:
x3[0:,0:2]

array([[[1, 2, 3],
        [5, 6, 7]]])

In [39]:
x3[0:,0::2]

array([[[ 1,  2,  3],
        [ 8,  9, 10]]])

In [40]:
x3[0:,0:,0::2]

array([[[ 1,  3],
        [ 5,  7],
        [ 8, 10]]])

In [41]:
x3

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [47]:
print(x3[0:,1,2])

[7]


In [48]:
x3[0][1][2]

7

# Filtering

    - To get important features we need to filter the data

In [50]:
a=np.arange(2,50)

In [51]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [53]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [58]:
a[a>=30]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [59]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [62]:
a[(a>=25)&(a<=40)]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

## Statistics 

In [63]:
x1

array([ 1,  2,  5, 66])

In [64]:
np.max(x1)

66

In [65]:
np.min(x1)

1

In [66]:
np.mean(x1)

18.5

In [67]:
np.median(x1)

3.5

In [68]:
np.sum(x1)

74

In [69]:
np.std(x1)

27.463612289718917

In [71]:
np.percentile(x1,25)

1.75

In [72]:
np.percentile(x1,100)

66.0

## Aggrigation Functions

In [76]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
x2.argmax() #returns index position of max element

5

In [82]:
x2.argmin()

0

In [83]:
x2.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

## Saving Data

In [84]:
x=np.random.rand(1,10)
x

array([[0.20977336, 0.06964308, 0.37837519, 0.50797923, 0.52909758,
        0.78394318, 0.17626198, 0.80936294, 0.50524038, 0.86709933]])

In [85]:
np.save("x.npy",x)

In [86]:
np.load("x.npy")

array([[0.20977336, 0.06964308, 0.37837519, 0.50797923, 0.52909758,
        0.78394318, 0.17626198, 0.80936294, 0.50524038, 0.86709933]])

## Numpy copy and view
- copy
    - changes will not be effected to the original array and vice versa
- view
    - changes will be effected to the original array if change in copied array and vice versa

In [92]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy() # shallow copy
print("copied array:",x)
print("main array:",arr)
arr[0]=40
print("copied array:",x)
print("main array:",arr)

copied array: [1 2 3 4 5]
main array: [1 2 3 4 5]
copied array: [1 2 3 4 5]
main array: [40  2  3  4  5]


In [97]:
import numpy as np
n1=np.array([11,22,33,44,55])
n2=n1.view()# deep copy
print("main array:",n1)
print("copied array:",n2)
n1[0]=99
print("main array:",n1)
print("copied array:",n2)
n2[0]=88
print("main array:",n1)
print("copied array:",n2)

main array: [11 22 33 44 55]
copied array: [11 22 33 44 55]
main array: [99 22 33 44 55]
copied array: [99 22 33 44 55]
main array: [88 22 33 44 55]
copied array: [88 22 33 44 55]


## Numpy Joining Arrays
- np.concatenate()

In [100]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.concatenate((a1,a2)))

[1 2 3 4 5 6]


In [106]:
import numpy as np
b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[7,8,9],[10,11,12]])
b3=np.concatenate((b1,b2),axis=1)
b3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [107]:
np.vstack((b1,b2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
np.hstack((b1,b2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Numpy Math Functions

- sin
- cos
- tan

In [109]:
a1=np.arange(1,100)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [110]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316,
       -0.15862267, -0.91652155, -0.83177474,  0.01770193,  0.85090352,
        0.90178835,  0.12357312, -0.76825466, -0.95375265, -0.26237485,
        0.67022918,  0.98662759,  0.39592515, -0.55878905, -0.99975517,
       -0.521551  ,  0.43616476,  0.99287265,  0.63673801, -0.30481062,
       -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,  0.82682868,
       -0.02655115, -0.85551998, -0.89792768, -0.11478481,  0.77

In [111]:
np.exp(a1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21, 1.40934908e+22, 3.83100800e+22,
       1.04137594e+23, 2.83075330e+23, 7.69478527e+23, 2.09165950e+24,
      

In [112]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [113]:
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145,
        0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
       -0.12796369,  0.76541405,  0.95507364,  0.26664293, -0.66693806,
       -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,  0.52532199,
       -0.43217794, -0.99233547, -0.64014434,  0.30059254,  0.96496603,
        0.7421542 , -0.16299078, -0.91828279, -0.82930983,  0.02212676,
        0.85322011,  0.89986683,  0.11918014, -0.77108022, -0.95241298,
       -0.25810164,  0.67350716,  0.98589658,  0.39185723, -0.56245385,
       -0.99964746, -0.5177698 ,  0.44014302,  0.99339038,  0.63

In [114]:
np.tan(a1)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
       -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,  7.75047091e+00,
       -8.40771255e-01,  3.10309661e-01,  3.61455441e+00, -1.11721493e+00,
        1.60656699e-01,  2.29138799e+00, -1.49838734e+00,  1.77046993e-02,
        1.61977519e+00, -2.08661353e+00, -1.24527568e-01,  1.20012724e+00,
       -3.17290855e+00, -2.71900612e-01,  9.03086149e-01, -6.05327238e+00,
       -4.31158197e-01,  