### Day Agenda
- Data Science Life Cycle
- Data Science Libraries

### Data Science Life Cycle

It involves 6-7 steps
1. Business Understanding
2. Data Preparation
3. Data Munging/Data Wrangling
    - feature selection
    - EDA(Exploratory data analysis)Tools
4. Model training
5. Model evaluation
6. Model Deployment
    - aws
    - IBM waston studio
7. Model tracking

### Data Analysis Libraries
- numpy
- pandas
- matplotlib
- seaborn
- scipy

## Numpy

- Numerical Python
- Developed in 2005 by Travis oliphant
- Create arrays 
    - Zero dimensional array
    - Single dimensional array
    - Two dimensional array
    - Multi dimensional array
- Linear algebra,Fourier Transforms,materics

In [3]:
import numpy

In [5]:
import numpy as np

In [7]:
np.__version__

'1.19.2'

## Creating arrays

In [9]:
import numpy as np
x=np.array(23)
print(x)

23


In [10]:
##check the dimension
np.ndim(x)

0

In [13]:
##1-D array
x1=np.array([12,23,4,5,6])
print(x1)
print(np.ndim(x1))

[12 23  4  5  6]
1


In [16]:
##2-D Array
x2=np.array([[1,2,3],[5,6,7]])
print(x2)
print(np.ndim(x2))

[[1 2 3]
 [5 6 7]]
2


In [17]:
## to get the no.of elements
np.size(x2)

6

In [18]:
## To get no.of rows and columns
np.shape(x2)

(2, 3)

In [19]:
## 3-D Array
x3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x3)
print(np.ndim(x3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


## Methods to create arrays
- Zeros
- Ones
- linspace
- logspace
- arange

In [22]:
a0=np.zeros(2)
print(a0)

[0. 0.]


In [24]:
a1=np.ones(5,dtype=int)
print(a1)

[1 1 1 1 1]


In [28]:
a=np.arange(1,12,2)

In [29]:
print(a)
np.size(a)

[ 1  3  5  7  9 11]


6

In [30]:
a1=a.reshape(2,3)

In [31]:
a1

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [32]:
li=np.logspace(1,5)
print(li)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


In [34]:
r=np.random.rand(3,2)

In [35]:
print(r)

[[0.29268204 0.57610991]
 [0.82070846 0.64917356]
 [0.88914383 0.18182365]]


## Accessing elements in Arrays
1. Indexing
    - +ve
    - -ve
2. Slicing
    - [start:stop:step]
3.Loop
    - for
    - while