## Classification
- binomial---2 output labels---0,1 or yes,no or true,false
- multinomial classification---0,1,2,3

### Logistic Regression
- uses sigmoid function b/w 0 and 1
- sigmoid function y=1/1+e^-z

In [44]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/Heart_disease.csv")

In [45]:
df

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [46]:
df['AHD'].unique()

array(['No', 'Yes'], dtype=object)

In [47]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [48]:
df["Thal"].mode()

0    normal
dtype: object

In [49]:
import numpy as np
df["Thal"].replace(np.nan,'normal',inplace=True)
df["Ca"].replace(np.nan,0,inplace=True)

In [50]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [51]:
df['Thal'].unique()

array(['fixed', 'normal', 'reversable'], dtype=object)

In [53]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [57]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['Thal']=label.fit_transform(df['Thal'])
df['ChestPain']=label.fit_transform(df['ChestPain'])
df['AHD']=label.fit_transform(df['AHD'])

In [58]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  AHD  
0      3  0.0     0    0  
1      2  3.0     1    1  
2      2  2.0     2    1  
3      3  0.0     1    0  
4      1  0.0     1    0

In [59]:
x=df.drop("AHD",axis=1)

In [60]:
x

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   
302   38    1          1     138   175    0        0    173      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     0  
1        2  3.0     1  
2        2  2.0     2  
3        3  0.0     1  
4        1  0.0     1  
..     ...  ...   ...  
298      2  0.0     2  
299      2  2.0     2  
300      2  1.0     2  
301      2  1.0     1  
302      1  0.0     1  

[303 rows x 13 columns]

In [61]:
y=df['AHD']

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x,y)

C:\Users\India\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [66]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  AHD  
0      3  0.0     0    0  
1      2  3.0     1    1  
2      2  2.0     2    1  
3      3  0.0     1    0  
4      1  0.0     1    0

In [68]:
model.predict([[63,1,3,145,233,1,2,150,0,2.3,3,0.0,0]])

array([0])

In [70]:
y_predict=model.predict(x_test)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Age        303 non-null    int64  
 1   Sex        303 non-null    int64  
 2   ChestPain  303 non-null    int32  
 3   RestBP     303 non-null    int64  
 4   Chol       303 non-null    int64  
 5   Fbs        303 non-null    int64  
 6   RestECG    303 non-null    int64  
 7   MaxHR      303 non-null    int64  
 8   ExAng      303 non-null    int64  
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64  
 11  Ca         303 non-null    float64
 12  Thal       303 non-null    int64  
 13  AHD        303 non-null    int32  
dtypes: float64(2), int32(2), int64(10)
memory usage: 30.9 KB


In [74]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_predict)*100

89.01098901098901

In [75]:
confusion_matrix(y_test,y_predict)

array([[39,  5],
       [ 5, 42]], dtype=int64)

In [ ]:
##accuracy=TP+TN/(TP+FP+FN+TN)

In [79]:
df['AHD'].value_counts()

0    164
1    139
Name: AHD, dtype: int64

### Apply logistic Regression to diabetes data and find accuracy and confusion matrix

In [96]:
data=pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/diabetes.csv")

In [97]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [98]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [99]:
x=data[data.columns[:-1]]

In [100]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [101]:
y=data['Outcome']

In [102]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x,y)

C:\Users\India\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [103]:
y_predict=model.predict(x_test)

In [104]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_predict)*100

80.51948051948052

In [105]:
confusion_matrix(y_test,y_predict)

array([[141,  19],
       [ 26,  45]], dtype=int64)

## balanced dataset
- 0--->90
- 1--->190
## imbalanced
- yes-->400
- no--->100
- for imbalanced we use precision,recall